name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cc23d67dafe69bb7b5fe8f6c3241475a2258325cb6039b6ebad6c2ea0d9cd7a"

[versions]
fabric = "0.8.7+build.201"
minecraft = "1.16-rc1"
yarn = "wow this field literally does nothing haha yes"
