name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f2002f7871051cb4b33b6cb4895ed3dcf69a6c92fbb50ecc88c9b80d75f3bd8"

[versions]
fabric = "0.8.7+build.201"
minecraft = "1.16-rc1"
yarn = "wow this field literally does nothing haha yes"
