name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "274b3fb33d02a70290f1caab2614280e975e9eb024e6e52cdef9c103ab5f2fc0"

[versions]
fabric = "0.8.7+build.201"
minecraft = "1.16-rc1"
yarn = "wow this field literally does nothing haha yes"
