name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fe49cc5f6ff8fcc3507144debc2f349672b98799593abffe4908ca6a86142fd"

[versions]
fabric = "0.8.4+build.198"
minecraft = "20w20b"
yarn = "20w20b+build.13"
