name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1adcd5c6e881ab2edc9acad9b169d0b142145545fa14b2dabac623749eeab46"

[versions]
fabric = "0.8.4+build.198"
minecraft = "20w20b"
yarn = "20w20b+build.13"
