name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0e31e8e7395d52d1f7c5a2abd57d0872dc8d20ab18fa1eec4389bc4e57c7213"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
