name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c275d3e5c5465987bf96235251cc85f48cc0d8dedbf8cefbfd184af9130998c4"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
