name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5620e67a757658effa0040687cc8fa621b4cc83fcedbc248b9948952a9ba2a84"

[versions]
fabric = "0.8.7+build.201"
minecraft = "1.16-rc1"
yarn = "wow this field literally does nothing haha yes"
