name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f2e668ba451fdb48b1f2b281b47d6dc9a1104ba8afb39fd20ec38a1b0b03453"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
