name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d981ff7fc408b4a82676dd63bea8a6344cc192b3bd8342786af931f469199ab"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
