name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8ca5d52774b8a33f38c3c10b3fe08763e7225a8a821cef13d9f08da4982e001"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
