name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac699f0811942e3e3b0ae3c77c8745b45025ca4f077a87782a370a74d30f46bb"

[versions]
fabric = "0.8.7+build.201"
minecraft = "1.16-rc1"
yarn = "wow this field literally does nothing haha yes"
