name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5ec32f8e0b5fd5b27a3afc3fec783c1d49d960df6707298d0a3bd8b321b3521"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
