name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "859b145f8a43e3176fc9d6dbc547f7ad43f64d3130e0c64eeceeb9fd7207cb6d"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
