name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cac44169d3aa3e932a729e3ce2d19b53c0d5eee7523af4c8309b2b80deacd26"

[versions]
fabric = "0.8.7+build.201"
minecraft = "1.16-rc1"
yarn = "wow this field literally does nothing haha yes"
