name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0ad1eb3b9ae177950906cc44ac1d51b85d593dece67e60fcb4edb79205f18bc"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
