name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46dfabe6d7f4d8feff013a9887af9126438b13a864cc4ce220ee93f9cd861fc5"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
