name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62e19a8738f8e9cdae918cd12a9ad6eb854cd677324ca5a5189a19aa481313df"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
