name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4b79892d21968c0af8800c8c283936e6e59cfb8cbac82f3ab6aa47fd7155318"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
