name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88917b37acad2879b50cfcc4f853746c94abffdc2c79ffdd615970d4a71ff118"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
