name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "771f5cd98e99b94134ec44d97ed04e324a1f2b63563d0af25c3ee844a9b1ddb8"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
