name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f2b8eb93a36901994eb148b2f05bf8fc5bbf000f30d4fccd95d88d9991714fe"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
