name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5b5d5cf1e73fefe9ff7a07edeff478f6e8bff3166d03fb7ac12c1f93498518c"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
