name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec56d210f14440cee58646813415709322044e9df3eac2bdc19fbb104a22db1d"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
