name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30275287ee32424ae8bcf26787920f68df0a2701b3f0adaa45b4015dcafc7e83"

[versions]
fabric = "0.8.2+build.194"
minecraft = "20w19a"
yarn = "20w19a+build.6"
