name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ded0823a14e7e3171e414bad108f46a2e0920aca19ac810245ed82c67b746f8e"

[versions]
fabric = "0.8.4+build.198"
minecraft = "20w20b"
yarn = "20w20b+build.13"
