name = "Temporary Modpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7b4cc9f17d49ef6efbee9a609859464263df2f7d609207a36d8c07e6d2290bf"

[versions]
fabric = "0.8.7+build.201"
minecraft = "1.16-rc1"
yarn = "wow this field literally does nothing haha yes"
