name = "Adabranium"
filename = "adabraniummod-1.1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2977/282/adabraniummod-1.1.3.1.jar"
hash-format = "murmur2"
hash = "3309370178"

[update]
[update.curseforge]
file-id = 2977282
project-id = 361599
release-channel = "beta"
