name = "Adorn"
filename = "Adorn-1.8.5+20w20b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2957/937/Adorn-1.8.5+20w20b.jar"
hash-format = "murmur2"
hash = "3661600137"

[update]
[update.curseforge]
file-id = 2957937
project-id = 320215
release-channel = "beta"
