name = "AFKPeace"
filename = "AFKPeace-1.16-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2958/509/AFKPeace-1.16-3.0.0.jar"
hash-format = "murmur2"
hash = "3223817192"

[update]
[update.curseforge]
file-id = 2958509
project-id = 380938
release-channel = "beta"
