name = "AFKPeace"
filename = "AFKPeace-1.16pre5-3.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2979/433/AFKPeace-1.16pre5-3.0.2.jar"
hash-format = "murmur2"
hash = "156330917"

[update]
[update.curseforge]
file-id = 2979433
project-id = 380938
release-channel = "beta"
