name = "Armor Visibility"
filename = "armor-visibility-1.16-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/523/armor-visibility-1.16-1.0.0.jar"
hash-format = "murmur2"
hash = "3001367326"

[update]
[update.curseforge]
file-id = 2985523
project-id = 387962
release-channel = "beta"
