name = "Bee Angry-est"
filename = "BeeAngryest-1.5.0+20w19a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2952/230/BeeAngryest-1.5.0+20w19a.jar"
hash-format = "murmur2"
hash = "2134266853"

[update]
[update.curseforge]
file-id = 2952230
project-id = 352296
release-channel = "beta"
