name = "Blur"
filename = "Blur-1.0.6-1.16-rc1.fabric.jar"
side = "both"

[download]
url = "https://github.com/Motschen/Blur/releases/download/1.0.6-1.16-rc1/Blur-1.0.6-1.16-rc1.fabric.jar"
hash-format = "sha256"
hash = "EFEABD48E6E05D01AFCB2F4B433A0BF0BF87E7BB6D1AD577339A125E62F4F9D2"