name = "Cardinal Components"
filename = "Cardinal-Components-API-2.4.0-nightly.1.16-rc1.build.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/476/Cardinal-Components-API-2.4.0-nightly.1.16-rc1.build.2.jar"
hash-format = "murmur2"
hash = "2585018381"

[update]
[update.curseforge]
file-id = 2985476
project-id = 318449
release-channel = "beta"
