name = "Conveyance"
filename = "conveyance-0.5.1+20w19a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2953/779/conveyance-0.5.1+20w19a.jar"
hash-format = "murmur2"
hash = "4267881334"

[update]
[update.curseforge]
file-id = 2953779
project-id = 355432
release-channel = "beta"
