name = "Conveyance"
filename = "conveyance-0.5.0+20w19a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2953/755/conveyance-0.5.0+20w19a.jar"
hash-format = "murmur2"
hash = "2136755609"

[update]
[update.curseforge]
file-id = 2953755
project-id = 355432
release-channel = "beta"
