name = "Couplings"
filename = "Couplings-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2843/209/Couplings-1.3.1.jar"
hash-format = "murmur2"
hash = "1140278930"

[update]
[update.curseforge]
file-id = 2843209
project-id = 311120
release-channel = "beta"
