name = "Diggus Maximus"
filename = "diggusmaximus-1.2.11-1.16-rc1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/986/diggusmaximus-1.2.11-1.16-rc1.jar"
hash-format = "murmur2"
hash = "276785344"

[update]
[update.curseforge]
file-id = 2985986
project-id = 341888
release-channel = "beta"
