name = "Enchanted ToolTips"
filename = "EnchantedToolTips-1.3.1-1.16-rc1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/5/EnchantedToolTips-1.3.1-1.16-rc1.jar"
hash-format = "murmur2"
hash = "3075528978"

[update]
[update.curseforge]
file-id = 2986005
project-id = 331965
release-channel = "beta"
