name = "Exotic Blocks"
filename = "exotic-blocks-mc116-1.4.132.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2970/334/exotic-blocks-mc116-1.4.132.jar"
hash-format = "murmur2"
hash = "2400911386"

[update]
[update.curseforge]
file-id = 2970334
project-id = 339561
release-channel = "beta"
