name = "[Fabric] Expanded Storage"
filename = "expandedstorage-5.1.3+1.16-rc1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/131/expandedstorage-5.1.3+1.16-rc1.jar"
hash-format = "murmur2"
hash = "2883534095"

[update]
[update.curseforge]
file-id = 2985131
project-id = 317856
release-channel = "beta"
