name = "[Fabric] Expanded Storage"
filename = "expandedstorage-5.1.2+1.16-rc1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2984/86/expandedstorage-5.1.2+1.16-rc1.jar"
hash-format = "murmur2"
hash = "3395833381"

[update]
[update.curseforge]
file-id = 2984086
project-id = 317856
release-channel = "beta"
