name = "ExtraDoors"
filename = "ExtraDoors-1.8.1-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2942/297/ExtraDoors-1.8.1-1.16.jar"
hash-format = "murmur2"
hash = "1709910827"

[update]
[update.curseforge]
file-id = 2942297
project-id = 341066
release-channel = "beta"
