name = "Fabric Passable Leaves"
filename = "passable-leaves-1.1.0.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/2955/998/passable-leaves-1.1.0.jar"
hash-format = "sha256"
hash = "A8A4A8ACC0C767CAC02C1EF9A89A59E2C1D7EC539755C43BED81CC143D31171F"

[update]
[update.curseforge]
file-id = 2911211
project-id = 357620
release-channel = "beta"
