name = "Fabric AutoSwitch"
filename = "autoswitch-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2939/908/autoswitch-1.4.0.jar"
hash-format = "murmur2"
hash = "131053577"

[update]
[update.curseforge]
file-id = 2939908
project-id = 347405
release-channel = "beta"
