name = "Fabric AutoSwitch"
filename = "autoswitch-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2979/410/autoswitch-2.4.0.jar"
hash-format = "murmur2"
hash = "3765605266"

[update]
[update.curseforge]
file-id = 2979410
project-id = 347405
release-channel = "beta"
