name = "Fabric Controlling"
filename = "fabriccontrolling-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/898/fabriccontrolling-1.1.0.jar"
hash-format = "murmur2"
hash = "3053990152"

[update]
[update.curseforge]
file-id = 2985898
project-id = 308841
release-channel = "beta"
