name = "Fabric API"
filename = "fabric-api-0.12.5+build.367-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2983/287/fabric-api-0.12.5+build.367-1.16.jar"
hash-format = "murmur2"
hash = "4116155785"

[update]
[update.curseforge]
file-id = 2983287
project-id = 306612
release-channel = "beta"
