name = "Fabric Passable Leaves"
filename = "passable-leaves-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2956/312/passable-leaves-1.2.0.jar"
hash-format = "murmur2"
hash = "1538933411"

[update]
[update.curseforge]
file-id = 2956312
project-id = 357620
release-channel = "beta"
