name = "Fabric AutoSwitch"
filename = "autoswitch-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2955/784/autoswitch-1.5.0.jar"
hash-format = "murmur2"
hash = "1318803007"

[update]
[update.curseforge]
file-id = 2955784
project-id = 347405
release-channel = "beta"
