name = "More Enchantments"
filename = "MoEnchantments-1.11.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2942/650/MoEnchantments-1.11.0.jar"
hash-format = "murmur2"
hash = "3593744911"

[update]
[update.curseforge]
file-id = 2942650
project-id = 320806
release-channel = "beta"
