name = "Flamingo"
filename = "Flamingo-1.16-pre2-1.18.jar"
side = "both"

[download]
url = "https://github.com/Yoghurt4C/Flamingo/releases/download/v1.18/Flamingo-1.16-pre2-1.18.jar"
hash-format = "sha256"
hash = "D4B44A01506FF32CA2D23FBBB138023A3212D7B0C44249EAB5AD96BDB733BEC5"