name = "FlightHelper"
filename = "flighthelper-1.16-rc1-fabric0.12.5-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2984/640/flighthelper-1.16-rc1-fabric0.12.5-1.2.jar"
hash-format = "murmur2"
hash = "3871764709"

[update]
[update.curseforge]
file-id = 2984640
project-id = 270840
release-channel = "beta"
