name = "Flowing Background"
filename = "FlowingBackground-1.1.0+20w20b.jar"
side = "both"

[option]
optional = true
description = "backgrounds with groove"
default = true

[download]
url = "https://edge.forgecdn.net/files/2959/143/FlowingBackground-1.1.0+20w20b.jar"
hash-format = "murmur2"
hash = "3132547561"

[update]
[update.curseforge]
file-id = 2959143
project-id = 380476
release-channel = "beta"
