name = "Giselbaer's Durability Viewer"
filename = "durabilityviewer-1.16-rc1-fabric0.12.5-1.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2984/633/durabilityviewer-1.16-rc1-fabric0.12.5-1.7.1.jar"
hash-format = "murmur2"
hash = "2611772688"

[update]
[update.curseforge]
file-id = 2984633
project-id = 262146
release-channel = "beta"
