name = "Gravel Ores (Fabric)"
filename = "gravel-ores-2.0.0-unstable.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2956/37/gravel-ores-2.0.0-unstable.jar"
hash-format = "murmur2"
hash = "642347070"

[update]
[update.curseforge]
file-id = 2956037
project-id = 382525
release-channel = "beta"
