name = "Gravestones"
filename = "gravestones-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/444/gravestones-1.3.0.jar"
hash-format = "murmur2"
hash = "813453305"

[update]
[update.curseforge]
file-id = 2985444
project-id = 373595
release-channel = "beta"
