name = "Hardcore Questing Mode Fabric"
filename = "HQM-0.2.0-SNAPSHOT.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/784/HQM-0.2.0-SNAPSHOT.jar"
hash-format = "murmur2"
hash = "3979691647"

[update]
[update.curseforge]
file-id = 2985784
project-id = 383748
release-channel = "beta"
