name = "Impersonate"
filename = "Impersonate-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/447/Impersonate-2.0.0.jar"
hash-format = "murmur2"
hash = "806086737"

[update]
[update.curseforge]
file-id = 2985447
project-id = 360333
release-channel = "beta"
