name = "Improved Stations (Fabric)"
filename = "improved-stations-2.0.0-unstable.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2905/308/improved-stations-2.0.0-unstable.jar"
hash-format = "murmur2"
hash = "3794037232"

[update]
[update.curseforge]
file-id = 2905308
project-id = 355914
release-channel = "beta"
