name = "JavaDungeons"
filename = "javadungeons-1.1.9+20w20b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2960/933/javadungeons-1.1.9+20w20b.jar"
hash-format = "murmur2"
hash = "2362258221"

[update]
[update.curseforge]
file-id = 2960933
project-id = 375052
release-channel = "beta"
