name = "Light Block - Fabric"
filename = "lightblock-1.16-pre2+1.0.1+build.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2977/160/lightblock-1.16-pre2+1.0.1+build.5.jar"
hash-format = "murmur2"
hash = "4098894524"

[update]
[update.curseforge]
file-id = 2977160
project-id = 383801
release-channel = "beta"
