name = "Lil Tater Reloaded"
filename = "LilTaterReloaded-1.1.2+1.16-pre7-rc1-BOOTLEG.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/439/LilTaterReloaded-1.1.2+1.16-pre7-rc1-BOOTLEG.jar"
hash-format = "murmur2"
hash = "2316693772"

[update]
[update.curseforge]
file-id = 2985439
project-id = 383066
release-channel = "beta"
