name = "Lil Tater Reloaded"
filename = "LilTaterReloaded-1.1.1+1.16-pre7-BOOTLEG.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2982/425/LilTaterReloaded-1.1.1+1.16-pre7-BOOTLEG.jar"
hash-format = "murmur2"
hash = "396810517"

[update]
[update.curseforge]
file-id = 2982425
project-id = 383066
release-channel = "beta"
