name = "Lithium (Fabric)"
filename = "lithium-fabric-mc20w14a-0.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2919/583/lithium-fabric-mc20w14a-0.5.0.jar"
hash-format = "murmur2"
hash = "2117967082"

[update]
[update.curseforge]
file-id = 2919583
project-id = 360438
release-channel = "beta"
