name = "Lithium (Fabric)"
filename = "lithium-fabric-mc20w19a-0.5.0-SNAPSHOT.jar"
side = "both"

[download]
url = "https://fibercraft.immibis.com/haykam/lithium-fabric-mc20w19a-0.5.0-SNAPSHOT.jar"
hash-format = "sha256"
hash = "161bc7ec9685e857e560a194935e98d1c90f9f83005a18b62efc29bd33244be8"