name = "Makkit"
filename = "makkit-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2981/978/makkit-1.0.2.jar"
hash-format = "murmur2"
hash = "374229781"

[update]
[update.curseforge]
file-id = 2981978
project-id = 381507
release-channel = "beta"
