name = "Mo' Structures"
filename = "mostructures-0.1.2+mc.1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2960/905/mostructures-0.1.2+mc.1.16.jar"
hash-format = "murmur2"
hash = "2479490948"

[update]
[update.curseforge]
file-id = 2960905
project-id = 378266
release-channel = "beta"
