name = "Mod Menu"
filename = "modmenu-1.12.1+build.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2978/153/modmenu-1.12.1+build.15.jar"
hash-format = "murmur2"
hash = "867750441"

[update]
[update.curseforge]
file-id = 2978153
project-id = 308702
release-channel = "beta"
