name = "Mod Menu"
filename = "modmenu-1.11.5+build.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2957/18/modmenu-1.11.5+build.10.jar"
hash-format = "murmur2"
hash = "271385320"

[update]
[update.curseforge]
file-id = 2957018
project-id = 308702
release-channel = "beta"
