name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.4.11+mc20w18a.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/2960/593/mousewheelie-1.4.11+mc20w18a.jar"
hash-format = "murmur2"
hash = "2816560927"

[update]
[update.curseforge]
file-id = 2960593
project-id = 317514
release-channel = "beta"
