name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.4.16+mc1.16-rc1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/2983/270/mousewheelie-1.4.16+mc1.16-rc1.jar"
hash-format = "murmur2"
hash = "62428171"

[update]
[update.curseforge]
file-id = 2983270
project-id = 317514
release-channel = "beta"
