name = "Mr. Pineapple's Food Mod"
filename = "mr-pineapples-food-mod-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2957/601/mr-pineapples-food-mod-1.0.0.jar"
hash-format = "murmur2"
hash = "2992372932"

[update]
[update.curseforge]
file-id = 2957601
project-id = 378933
release-channel = "beta"
