name = "Name Pain"
filename = "NamePain-1.16.rc1-Fabric-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/972/NamePain-1.16.rc1-Fabric-1.2.2.jar"
hash-format = "murmur2"
hash = "260198288"

[update]
[update.curseforge]
file-id = 2985972
project-id = 366263
release-channel = "beta"
