name = "Nice To Have (Fabric)"
filename = "nice-to-have-1.3.0-beta.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2960/316/nice-to-have-1.3.0-beta.6.jar"
hash-format = "murmur2"
hash = "3315235035"

[update]
[update.curseforge]
file-id = 2960316
project-id = 332704
release-channel = "beta"
