name = "Not Enough Crashes"
filename = "notenoughcrashes-1.2.4+1.16-pre2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2974/808/notenoughcrashes-1.2.4+1.16-pre2.jar"
hash-format = "murmur2"
hash = "3955596009"

[update]
[update.curseforge]
file-id = 2974808
project-id = 353890
release-channel = "beta"
