name = "Ok Zoomer"
filename = "okzoomer-4.0.0-alpha.3.1.16.pre5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/2980/374/okzoomer-4.0.0-alpha.3.1.16.pre5.jar"
hash-format = "murmur2"
hash = "3459770794"

[update]
[update.curseforge]
file-id = 2980374
project-id = 354047
release-channel = "beta"
