name = "Packages"
filename = "packages+20w20b-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2958/51/packages+20w20b-1.0.jar"
hash-format = "murmur2"
hash = "3815480752"

[update]
[update.curseforge]
file-id = 2958051
project-id = 383733
release-channel = "beta"
