name = "Pehkui"
filename = "Pehkui-1.5.1+1.16-pre2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2975/1/Pehkui-1.5.1+1.16-pre2.jar"
hash-format = "murmur2"
hash = "2680685916"

[update]
[update.curseforge]
file-id = 2975001
project-id = 319596
release-channel = "beta"
