name = "Phosphor (Fabric)"
filename = "phosphor-fabric-mc20w15a-0.5.2-SNAPSHOT.jar"
side = "both"

[download]
url = "https://fibercraft.immibis.com/haykam/phosphor-fabric-mc20w15a-0.5.2-SNAPSHOT.jar"
hash-format = "sha256"
hash = "01ec0a2078ed4e49d40732a3df2865db56003e72796c93ca1ba03048e499e6bc"