name = "Phosphor (Fabric)"
filename = "phosphor-fabric-mc20w15a-0.5.2-SNAPSHOT.jar"
side = "both"

[download]
url = "https://fibercraft.immibis.com/haykam/phosphor-fabric-mc20w19a-0.6.0-SNAPSHOT.jar"
hash-format = "sha256"
hash = "7102e712d1f8df19f01fc2fecfb3e6804f16d68ad1272f9bb6e131d8b5a4f230"