name = "Pling"
filename = "pling-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2894/100/pling-1.1.0.jar"
hash-format = "murmur2"
hash = "2037858881"

[update]
[update.curseforge]
file-id = 2894100
project-id = 365521
release-channel = "beta"
