name = "Presence Footsteps"
filename = "PresenceFootsteps-r25+20w20b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2958/183/PresenceFootsteps-r25+20w20b.jar"
hash-format = "murmur2"
hash = "3255895281"

[update]
[update.curseforge]
file-id = 2958183
project-id = 334259
release-channel = "beta"
