name = "Rare Ice (Forge/Fabric)"
filename = "rare-ice-0.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2956/316/rare-ice-0.1.2.jar"
hash-format = "murmur2"
hash = "3684498707"

[update]
[update.curseforge]
file-id = 2956316
project-id = 373774
release-channel = "beta"
