name = "Roughly Enough Items (REI)"
filename = "RoughlyEnoughItems-4.3.6-unstable.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2952/235/RoughlyEnoughItems-4.3.6-unstable.jar"
hash-format = "murmur2"
hash = "2684651159"

[update]
[update.curseforge]
file-id = 2952235
project-id = 310111
release-channel = "beta"
