name = "Roughly Enough Items (REI)"
filename = "RoughlyEnoughItems-4.3.10-unstable.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2960/651/RoughlyEnoughItems-4.3.10-unstable.jar"
hash-format = "murmur2"
hash = "3883497669"

[update]
[update.curseforge]
file-id = 2960651
project-id = 310111
release-channel = "beta"
