name = "Roughly Enough Resources"
filename = "rer-2.0.0-unstable.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2956/360/rer-2.0.0-unstable.jar"
hash-format = "murmur2"
hash = "281695305"

[update]
[update.curseforge]
file-id = 2956360
project-id = 325625
release-channel = "beta"
