name = "RSWires"
filename = "rswires-4.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2984/225/rswires-4.8.0.jar"
hash-format = "murmur2"
hash = "2182819583"

[update]
[update.curseforge]
file-id = 2984225
project-id = 286328
release-channel = "beta"
