name = "RSWires"
filename = "rswires-4.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2956/501/rswires-4.4.0.jar"
hash-format = "murmur2"
hash = "1013357543"

[update]
[update.curseforge]
file-id = 2956501
project-id = 286328
release-channel = "beta"
