name = "ShulkerBoxTooltip"
filename = "shulkerboxtooltip-2.0.3+20w19a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2953/173/shulkerboxtooltip-2.0.3+20w19a.jar"
hash-format = "murmur2"
hash = "3798991300"

[update]
[update.curseforge]
file-id = 2953173
project-id = 315811
release-channel = "beta"
