name = "Simple Teleporters (Fabric)"
filename = "simpleteleporters-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/92/simpleteleporters-2.2.0.jar"
hash-format = "murmur2"
hash = "3913752253"

[update]
[update.curseforge]
file-id = 2986092
project-id = 334011
release-channel = "beta"
