name = "Simply Strawberries"
filename = "simplystrawberrys-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2978/604/simplystrawberrys-1.2.0.jar"
hash-format = "murmur2"
hash = "445645200"

[update]
[update.curseforge]
file-id = 2978604
project-id = 363572
release-channel = "beta"
