name = "Simplex Terrain Generation"
filename = "simplexterrain-0.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2959/171/simplexterrain-0.6.0.jar"
hash-format = "murmur2"
hash = "1963117076"

[update]
[update.curseforge]
file-id = 2959171
project-id = 352997
release-channel = "beta"
