name = "Staff of Building"
filename = "staffofbuilding-1.0.0_20w19a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2959/554/staffofbuilding-1.0.0_20w19a.jar"
hash-format = "murmur2"
hash = "1706248536"

[update]
[update.curseforge]
file-id = 2959554
project-id = 382694
release-channel = "beta"
