name = "SuperAxes"
# Note to all: DO NOT PUT SQUARE BRACKETS IN YOUR FILE NAME :(
filename = "SuperAxes-1.1.1+1.16-pre2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/440/%5B1.16-pre2%5D SuperAxes-1.1.1.jar"
hash-format = "murmur2"
hash = "3562653488"

[update]
[update.curseforge]
file-id = 2985440
project-id = 360386
release-channel = "beta"
