name = "Parry"
filename = "parry-1.0__1.16-pre2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2977/325/parry-1.0__1.16-pre2.jar"
hash-format = "murmur2"
hash = "2760459594"

[update]
[update.curseforge]
file-id = 2977325
project-id = 389010
release-channel = "beta"
