name = "Tech Reborn"
filename = "TechReborn-1.16-3.4.0+build.43.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2985/83/TechReborn-1.16-3.4.0+build.43.jar"
hash-format = "murmur2"
hash = "2246338504"

[update]
[update.curseforge]
file-id = 2985083
project-id = 233564
release-channel = "beta"
