name = "Torcherino"
filename = "torcherino-2.11.67+1.16-rc1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2983/720/torcherino-2.11.67+1.16-rc1.jar"
hash-format = "murmur2"
hash = "3104176668"

[update]
[update.curseforge]
file-id = 2983720
project-id = 236794
release-channel = "beta"
