name = "Towelette"
filename = "Towelette-3.2.0+20w19a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2952/524/Towelette-3.2.0+20w19a.jar"
hash-format = "murmur2"
hash = "878764373"

[update]
[update.curseforge]
file-id = 2952524
project-id = 309338
release-channel = "beta"
