name = "Trap Expansion  (Fabric)"
filename = "trapexpansion-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2986/47/trapexpansion-1.3.2.jar"
hash-format = "murmur2"
hash = "251879297"

[update]
[update.curseforge]
file-id = 2986047
project-id = 334018
release-channel = "beta"
