name = "Traverse"
filename = "traverse-2.2.5+build.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2946/866/traverse-2.2.5+build.14.jar"
hash-format = "murmur2"
hash = "3342404199"

[update]
[update.curseforge]
file-id = 2946866
project-id = 308777
release-channel = "beta"
