name = "Trees Do Not Float"
filename = "tdnf-mc116-1.9.83.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2958/701/tdnf-mc116-1.9.83.jar"
hash-format = "murmur2"
hash = "4236421939"

[update]
[update.curseforge]
file-id = 2958701
project-id = 323354
release-channel = "beta"
