name = "True Darkness"
filename = "darkness-mc116-1.5.39.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/2970/747/darkness-mc116-1.5.39.jar"
hash-format = "murmur2"
hash = "2539672706"

[update]
[update.curseforge]
file-id = 2970747
project-id = 337243
release-channel = "beta"

[option]
optional = true
description = "spooky dark mod"
default = true
