name = "Unbad Redstone"
filename = "unbad-redstone-1.16-rc1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2984/380/unbad-redstone-1.16-rc1-1.0.0.jar"
hash-format = "murmur2"
hash = "1525261439"

[update]
[update.curseforge]
file-id = 2984380
project-id = 390808
release-channel = "beta"
