name = "Vanilla+ Biomes"
filename = "vanillaplusbiomes-0.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2966/234/vanillaplusbiomes-0.2.1.jar"
hash-format = "murmur2"
hash = "809317733"

[update]
[update.curseforge]
file-id = 2966234
project-id = 367944
release-channel = "beta"
