name = "Void Fog [Fabric]"
filename = "Void-Fog-2.3.2+20w20b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2958/188/Void-Fog-2.3.2+20w20b.jar"
hash-format = "murmur2"
hash = "2282685054"

[update]
[update.curseforge]
file-id = 2958188
project-id = 353648
release-channel = "beta"
