name = "VoxelMap"
filename = "fabricmod_VoxelMap-1.9.18_for_1.16(20w20a).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2956/247/fabricmod_VoxelMap-1.9.18_for_1.16(20w20a).jar"
hash-format = "murmur2"
hash = "4163392990"

[update]
[update.curseforge]
file-id = 2956247
project-id = 225179
release-channel = "beta"
