name = "Winged"
filename = "winged-1.16-pre8-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2982/718/winged-1.16-pre8-1.0.jar"
hash-format = "murmur2"
hash = "3502567671"

[update]
[update.curseforge]
file-id = 2982718
project-id = 381349
release-channel = "beta"
