name = "Winged"
filename = "winged-0.1-techdemo.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2949/568/winged-0.1-techdemo.jar"
hash-format = "murmur2"
hash = "2438119587"

[update]
[update.curseforge]
file-id = 2949568
project-id = 381349
release-channel = "beta"
